on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      caller_job_name:
        default: jekyll-site-html-proofer
        description: The name of the job that calls this one
        required: false
        type: string
      command:
        description: The file or command to run
        required: true
        type: string
      notify_pr:
        default: false
        description: Whether to notify the PR about failures/success runs
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install Ruby and Bundle Install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll Build
        run: JEKYLL_ENV=production bundle exec jekyll build --destination _site

      - name: HTML Proofer
        run: |
          if ${{ inputs.notify_pr }}; then
            if ${{ inputs.command }}; then
              echo "status=success" >> $GITHUB_ENV
            else
              echo "status=fail" >> $GITHUB_ENV
            fi
          else
            ${{ inputs.command }}
          fi

      - id: job_log_url
        if: github.event_name == 'pull_request' && inputs.notify_pr == 'true'
        name: Get Job Log URL
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          job_name: ${{ inputs.caller_job_name }} / ${{ github.job }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'fail'
        name: Pull Request Failure Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment_tag: jekyll-site-html-proofer
          message: |
            :warning: Latest run of Jekyll Site HTML Proofer **failed**: ${{ steps.job_log_url.outputs.html_url }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'success'
        name: Pull Request Success Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment_tag: jekyll-site-html-proofer
          message: |
            :white_check_mark: Latest run of Jekyll Site HTML Proofer **succeeded**: ${{ steps.job_log_url.outputs.html_url }}
